spring.application.name=EcosDaGuerra

# 1. Configuração do Spring (127.0.0.1 é mais seguro que localhost aqui)
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/ecos_guerra_db
spring.datasource.username=postgres
spring.datasource.password=mlovatto

# 2. Configuração do JPA
spring.jpa.hibernate.ddl-auto=validate

# 3. Configuração BLINDADA do Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.url=jdbc:postgresql://127.0.0.1:5432/ecos_guerra_db
spring.flyway.user=postgres
spring.flyway.password=mlovatto